apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: clickhouse-zookeeper
  namespace: clickhouse
spec:
  replicas: 1
  image:
    repository: pravega/zookeeper
    tag: 0.2.15
  pod:
    serviceAccountName: sa-zookeeper
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
  storageType: persistence
  persistence:
    spec:
      resources:
        requests:
          storage: 2Gi












